[theme]
primaryColor = "#3F2739"  # This is the color of the sidebar
backgroundColor = "#616247FF"  # Light pink for the main background
secondaryBackgroundColor = "#DAA03DFF"  # Optional lighter shade for other elements
textColor = "#fffffff"  # Main text color (black)
font = "sans serif"  # Default font family
